package org.idempiere

import kotliquery.Row

internal val simpleMapperId = mapOf(
    "AD_Private_Access" to { id: Int -> org.compiere.orm.MPrivateAccess(id) },
    "AD_User_OrgAccess" to { id: Int -> org.compiere.orm.MUserOrgAccess(id) },
    "AD_Sequence_No" to { id: Int -> org.compiere.orm.X_AD_Sequence_No(id) },
    "AD_TreeNodeBP" to { id: Int -> org.compiere.orm.X_AD_TreeNodeBP(id) },
    "AD_TreeNodeMM" to { id: Int -> org.compiere.orm.X_AD_TreeNodeMM(id) },
    "AD_TreeNodePR" to { id: Int -> org.compiere.orm.X_AD_TreeNodePR(id) },
    "AD_Ref_Table" to { id: Int -> org.compiere.orm.MRefTable(id) },
    "AD_Table_Access" to { id: Int -> org.compiere.orm.MTableAccess(id) },
    "AD_Column_Access" to { id: Int -> org.compiere.orm.MColumnAccess(id) },
    "AD_User_Roles" to { id: Int -> org.compiere.orm.MUserRoles(id) },
    "AD_Role_Included" to { id: Int -> org.compiere.orm.X_AD_Role_Included(id) },
    "AD_Role_OrgAccess" to { id: Int -> org.compiere.orm.MRoleOrgAccess(id) },
    "AD_PInstance_Log" to { id: Int -> org.compiere.orm.X_AD_PInstance_Log(id) },
    "AD_Tree" to { id: Int -> org.compiere.orm.MTree_Base(id) },
    "AD_Element" to { id: Int -> org.compiere.orm.M_Element(id) },
    "AD_Table" to { id: Int -> org.compiere.orm.MTable(id) },
    "AD_Column" to { id: Int -> org.compiere.orm.MColumn(id) },
    "C_DocType" to { id: Int -> org.compiere.orm.MDocType(id) },
    "AD_Ref_List" to { id: Int -> org.compiere.orm.MRefList(id) },
    "AD_Role" to { id: Int -> org.compiere.orm.MRole(id) },
    "AD_StorageProvider" to { id: Int -> org.compiere.orm.X_AD_StorageProvider(id) },
    "AD_EntityType" to { id: Int -> org.compiere.orm.MEntityType(id) },
    "AD_Reference" to { id: Int -> org.compiere.orm.X_AD_Reference(id) },
    "AD_Org" to { id: Int -> org.compiere.orm.MOrg(id) },
    "AD_Sequence" to { id: Int -> org.compiere.orm.MSequence(id) },
    "AD_SysConfig" to { id: Int -> org.compiere.orm.MSysConfig(id) },
    "AD_ViewColumn" to { id: Int -> org.compiere.orm.MViewColumn(id) },
    "AD_TableIndex" to { id: Int -> org.compiere.orm.MTableIndex(id) },
    "AD_IndexColumn" to { id: Int -> org.compiere.orm.MIndexColumn(id) },
    "AD_ViewComponent" to { id: Int -> org.compiere.orm.MViewComponent(id) }
)
internal val simpleMapperRow = mapOf(
    "AD_Private_Access" to { row: Row -> org.compiere.orm.MPrivateAccess(row) },
    "AD_User_OrgAccess" to { row: Row -> org.compiere.orm.MUserOrgAccess(row) },
    "AD_Sequence_No" to { row: Row -> org.compiere.orm.X_AD_Sequence_No(row) },
    "AD_TreeNodeBP" to { row: Row -> org.compiere.orm.X_AD_TreeNodeBP(row) },
    "AD_TreeNodeMM" to { row: Row -> org.compiere.orm.X_AD_TreeNodeMM(row) },
    "AD_TreeNodePR" to { row: Row -> org.compiere.orm.X_AD_TreeNodePR(row) },
    "AD_Ref_Table" to { row: Row -> org.compiere.orm.MRefTable(row) },
    "AD_Table_Access" to { row: Row -> org.compiere.orm.MTableAccess(row) },
    "AD_Column_Access" to { row: Row -> org.compiere.orm.MColumnAccess(row) },
    "AD_User_Roles" to { row: Row -> org.compiere.orm.MUserRoles(row) },
    "AD_Role_Included" to { row: Row -> org.compiere.orm.X_AD_Role_Included(row) },
    "AD_Role_OrgAccess" to { row: Row -> org.compiere.orm.MRoleOrgAccess(row) },
    "AD_PInstance_Log" to { row: Row -> org.compiere.orm.X_AD_PInstance_Log(row) },
    "AD_Tree" to { row: Row -> org.compiere.orm.MTree_Base(row) },
    "AD_Element" to { row: Row -> org.compiere.orm.M_Element(row) },
    "AD_Table" to { row: Row -> org.compiere.orm.MTable(row) },
    "AD_Column" to { row: Row -> org.compiere.orm.MColumn(row) },
    "C_DocType" to { row: Row -> org.compiere.orm.MDocType(row) },
    "AD_Ref_List" to { row: Row -> org.compiere.orm.MRefList(row) },
    "AD_Role" to { row: Row -> org.compiere.orm.MRole(row) },
    "AD_StorageProvider" to { row: Row -> org.compiere.orm.X_AD_StorageProvider(row) },
    "AD_EntityType" to { row: Row -> org.compiere.orm.MEntityType(row) },
    "AD_Reference" to { row: Row -> org.compiere.orm.X_AD_Reference(row) },
    "AD_Org" to { row: Row -> org.compiere.orm.MOrg(row) },
    "AD_Sequence" to { row: Row -> org.compiere.orm.MSequence(row) },
    "AD_SysConfig" to { row: Row -> org.compiere.orm.MSysConfig(row) },
    "AD_ViewColumn" to { row: Row -> org.compiere.orm.MViewColumn(row) },
    "AD_TableIndex" to { row: Row -> org.compiere.orm.MTableIndex(row) },
    "AD_IndexColumn" to { row: Row -> org.compiere.orm.MIndexColumn(row) },
    "AD_ViewComponent" to { row: Row -> org.compiere.orm.MViewComponent(row) }
)
